export {FILAS, COLUMNAS, PORTAVIONES, ACORAZADOS, CRUCEROS, DESTRUCTORES, SUBMARINOS, DISPAROS};

const FILAS = 10;
const COLUMNAS = 10;
const PORTAVIONES = 1;
const ACORAZADOS = 1;
const CRUCEROS = 3;
const DESTRUCTORES = 2;
const SUBMARINOS = 2;
const DISPAROS = 100;

